language: python

python:
  - 3.5.0

services:
  - postgresql

env:
  - DJANGO=1.8.6

before_install:
  - export DJANGO_SETTINGS_MODULE=christmas_crowdsource.travis-settings
  - export PYTHONPATH=$HOME/builds/fredoflynn/Christmas-Crowdsource
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet
  - pip install coveralls

before_script:
  - psql -c "CREATE DATABASE christmas_list;" -U postgres
#  - python manage.py migrate

script:
  - python mannage.py migrate
#  - coverage run --source='.' manage.py test users christmas_list api

after_success:
#  - coveralls
  - python manage.py test
